apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-pod
data:
  workflow-pod.yaml: |
    ---
    apiVersion: v1
    kind: PodTemplate
    metadata:
      name: workflow-pod
    spec:
      serviceAccountName: runner
      securityContext:
        fsGroup: 1001
