{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-pod
data:
  workflow-pod.yaml: |
    ---
    apiVersion: v1
    kind: PodTemplate
    metadata:
      name: {{ .Values.configMap.name }}
      {{- with .Values.configMap.metaLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.configMap.spec }}
    spec:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
