{{- if .Values.datasources.loki-tpl.enabled -}}
{{- $ds := .Values.datasources.loki-tpl }}
{{- range $name, $env := .Values.datasources.loki-tpl.externalEnvs }}
{{- $envName := tpl $name $ -}}

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    {{- include "grafana-datasources.labels" $ | nindent 4 }}
  name: loki-{{ $envName }}
spec:
  {{- with $ds.selector }}
  instanceSelector:
    matchLabels:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  resyncPeriod: {{ $ds.resyncPeriod | default "30s" }}
  {{- if $ds.allowCrossNamespaceImport }}
  allowCrossNamespaceImport: {{ $ds.allowCrossNamespaceImport }}
  {{- end }}
  uid: loki-{{ $envName }}
  {{- with $ds.datasource }}
  datasource:
    name: loki-{{ $envName }}
    url: https://loki.{{ tpl $env.domain $ }}
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $ds.plugins }}
  plugins:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $ds.valuesFrom }}
  valuesFrom:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}

{{- end }}
{{- end }}
