{{- range $cl_filter_name, $cl_filter_obj :=  .Values.clusterFilters }}
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: {{ $cl_filter_name }}
  labels:
{{- include "fluentbit-filters.labels" $ | nindent 4 }}
{{- with $cl_filter_obj.labels }}
{{- tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with $.Values.labels }}
{{- tpl (toYaml .) $ | nindent 4 }}
{{- end }}
spec:
  {{- with $cl_filter_obj.filters }}
  filters:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $cl_filter_obj.logLevel}}
  logLevel: {{ tpl . $ | quote }}
  {{- end }}
  {{- with $cl_filter_obj.match}}
  match: {{ tpl . $ | quote }}
  {{- end }}
  {{- with $cl_filter_obj.matchRegEx}}
  matchRegEx: {{ tpl . $ | quote }}
  {{- end }}
  {{- with $cl_filter_obj.ordinal}}
  ordinal: {{ tpl . $ | quote }}
  {{- end }}
{{- end }}
