apiVersion: v2
appVersion: "1.0"
description: Chart for configuring and installing redis failover instances using redis operator
name: redis-operated
version: 0.1.0

dependencies:
  - name: core
    version: 0.1.0
    repository: file://../../app/core
  - name: prometheus-lib
    version: 0.1.0
    repository: file://../../prometheus/lib
