sentinel:
  exporter:
    enabled: false
redis:
  exporter:
    enabled: false
auth: {}
bootstrapNode: {}
labelWhitelist: {}
redis-podmonitor:
  enabled: false
sentinel-podmonitor:
  enabled: false

redisServiceMonitor:
  enabled: false
  prometheusSelector: {}
  labels: {}
  targetLabels: []
  endpoints:
  - port: http-metrics
    path: /metrics

sentinelServiceMonitor:
  enabled: false
  prometheusSelector: {}
  labels: {}
  targetLabels: []
  endpoints:
  - targetPort: 9355
    path: /metrics
