parsers: {}

clusterParsers: {}

multilineParsers: {}
#  test:
#    type: "regex"
#    flushTimeout: 1000
#    keyContent: "log"
#    rules:
#      - start: "start_state"
#        regex: '/^\[?(\d+\-\d+\-\d+ \d+\:\d+\:\d+(\.\d+)?)\]? /'
#        next: "cont"
#      - start: "cont"
#        regex: '/^com\..*/'
#        next: "cont"
#      - start: "cont"
#        regex: '/^\s+.*/'
#        next: "cont"
#      - start: "cont"
#        regex: '/^Caused.*$/'
#        next: "cont"

clusterMultilineParsers: {}
#  test:
#    type: "regex"
#    flushTimeout: 1000
#    keyContent: "log"
#    rules:
#      - start: "start_state"
#        regex: '/^\[?(\d+\-\d+\-\d+ \d+\:\d+\:\d+(\.\d+)?)\]? /'
#        next: "cont"
#      - start: "cont"
#        regex: '/^com\..*/'
#        next: "cont"
#      - start: "cont"
#        regex: '/^\s+.*/'
#        next: "cont"
#      - start: "cont"
#        regex: '/^Caused.*$/'
#        next: "cont"
