apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-operated.fullname" . }}
{{- if .Values.secret.annotations }}
  annotations:
{{ toYaml .Values.secret.annotations | indent 4 }}
{{- end }}
  labels:
{{- if .Values.secret.labels }}
{{ toYaml .Values.secret.labels | indent 4 }}
    {{- include "alertmanager-operated.labels" . | nindent 4 }}
{{- else }}
    {{- include "alertmanager-operated.labels" . | nindent 4 }}
{{- end }}
data:
  alertmanager.yaml: {{ tpl (toYaml .Values.config) . | b64enc | quote }}
