{{- $app_configs := ternary .Values.global.configs .Values.configs ( not .Values.configs) }}
{{- if $app_configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "chainlink.fullname" . }}-cm
data:
  {{- with $app_configs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
