{{- $app_secrets := ternary .Values.global.secrets .Values.secrets  ( not .Values.secrets) }}
{{- if $app_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "chainlink.fullname" . }}-secret
type: Opaque
data:
  default.toml: | 
  {{- $app_secrets | nindent 4 }}
{{- end }}
