labels: {}

externalEnvs: {}
envApps: {}
appOverrides: {}

repository:
  revision: '{{ .Values.global.repo.revision }}'
  paths:
    charts: argocd/charts/infra/charts
    crds: argocd/charts/infra/crds
    manifests: "argocd/environments/{{ .Values.global.env.cloud_short_name }}/manifests"
    app_charts: argocd/charts/app
    env_from_charts: ../../../../environments/{{ .Values.global.env.cloud_short_name }}
    env_from_app_charts: ../../../environments/{{ .Values.global.env.cloud_short_name }}
    globals_from_app_charts: ../../infra/charts/globals.yaml
    globals_from_charts: ../globals.yaml


manifests:
  enabled: false
  directory: {}
  revision:
  labels: {}
  finalizers: {}
  syncPolicy: {}

crds:
  enabled: false
  revision:
  operators: {}
#    argocd:
#      enabled: true
#    grafana-operator:
#      enabled: true
#    prometheus-operator:
#      enabled: true
#    cert-manager:
#      enabled: true
#      directory:
#        recurse: true
#    external-dns:
#      enabled: true
#      revision: test
#    konghq:
#      enabled: true
#    postgres-operator:
#      enabled: true
#    redis-operator:
#      enabled: true
#    rabbitmq-cluster:
#      enabled: true
#    rabbitmq-messaging-topology:
#      enabled: true
#    fluent-operator:
#      enabled: true

  labels: {}
  finalizers: {}
  syncPolicy:
    syncOptions:
      - ServerSideApply=true

chart_apps:
  rabbitmq:
    enabled: false
    globalValues:
      access:
        roles: ["admin", "dev"]
  redis:
    enabled: false
  external-dns:
    enabled: false
    values: |
      external-dns:
        provider: {{ .Values.global.env.dns.provider | quote }}
  gha-runner:
    enabled: false
    values: |
      gha-runner:
        listenerTemplate:
          metadata:
            annotations:
              argocd.argoproj.io/tracking-id: gha-runner-{{ .Values.global.env.cloud_short_name }}:actions.github.com/Pod:gha-runner/gha-runner-{{ .Values.global.env.cloud_short_name }}
        resourceMeta:
          autoscalingListener:
            annotations:
              argocd.argoproj.io/tracking-id: gha-runner-{{ .Values.global.env.cloud_short_name }}:actions.github.com/AutoscalingListener:gha-runner/gha-runner-{{ .Values.global.env.cloud_short_name }}
  gha-runner-app:
    enabled: false
    chart: "{{ .Values.repository.paths.charts }}/gha-runner"
    values: |
      workflowConfigMap:
        spec:
          serviceAccountName: runner-app
      gha-runner:
        listenerTemplate:
          metadata:
            annotations:
              argocd.argoproj.io/tracking-id: gha-runner-app-{{ .Values.global.env.cloud_short_name }}:actions.github.com/Pod:gha-runner-app/gha-runner-app-{{ .Values.global.env.cloud_short_name }}
        resourceMeta:
          autoscalingListener:
            annotations:
              argocd.argoproj.io/tracking-id: gha-runner-app-{{ .Values.global.env.cloud_short_name }}:actions.github.com/AutoscalingListener:gha-runner-app/gha-runner-app-{{ .Values.global.env.cloud_short_name }}
  gha-operator:
    enabled: false
  pomerium:
    enabled: false
  postgres:
    enabled: false
    globalValues:
      access:
        roles: ["admin", "dev", "pm", "qa"]
  grafana:
    enabled: false
    globalValues:
      access:
        roles: ["admin", "dev", "pm", "qa"]
    values: |
      {{- if .Values.externalEnvs }}
      datasource:
        datasources:
          {{- range $env_name, $env_obj := .Values.externalEnvs }}
          loki-{{ tpl $env_name $ }}:
            enabled: true
            uid: loki-{{ tpl $env_name $ }}
            selector:
              grafana: main
            datasource:
              type: loki
              isDefault: false
              access: proxy
              jsonData:
                manageAlerts: 'false'
                timeout: 300
              url: https://loki.{{ $env_obj.domain }}
          {{- end }}
      {{- end }}
  konghq:
    enabled: false
    globalValues:
      ingress:
        class: konghq
  cert-manager:
    enabled: false
  argocd:
    enabled: false
    globalValues:
      access:
        roles: ["admin", "dev"]
    values: |
      argocd:
        externalRedis:
          host: argocd-{{ .Values.global.env.cloud_short_name }}-redis-cluster-master
  prometheus:
    enabled: false
    values: |
      operator:
        prometheusOperator:
          fullnameOverride: "prometheus-{{ .Values.global.env.cloud_short_name }}-operator"
  fluent:
    enabled: false
    values: |
      {{- if eq .Values.global.env.cloud.name "gcp" }}
      fluentbit-gcp:
        enabled: true
      {{- end }}
  thanos:
    enabled: false
    values: |
      {{- if eq .Values.global.env.type "internal" }}
      thanos:
        query:
          stores:
            - {{ printf "thanos-%s-storegateway:10901" .Values.global.env.cloud_short_name }}
            - {{ printf "prometheus-%s-prometheus-main-thanos:8080" .Values.global.env.cloud_short_name }}
            {{- if .Values.externalEnvs }}
            - {{ printf "thanos-external-%s-query-grpc:10901" .Values.global.env.cloud_short_name }}
            {{- end }}
      {{- end }}
  thanos-external:
    enabled: false
    chart: '{{ .Values.repository.paths.charts }}/thanos'
    values: |
      thanos:
        query:
          stores:
            {{- range $env_name, $env_obj := .Values.externalEnvs }}
            - {{ printf "thanos.%s:443" $env_obj.domain }}
            - {{ printf "thanos-store.%s:443" $env_obj.domain }}
            {{- end }}
      secrets:
        thanos:
          enabled: false

  loki:
    enabled: false
    values: |
      loki:
        nameOverride: "loki-{{ .Values.global.env.cloud_short_name }}"
        loki:
          compactor:
            delete_request_store: "{{ .Values.global.env.cloud.buckets.type }}"
          storage:
            type: "{{ .Values.global.env.cloud.buckets.type }}"
            bucketNames:
              chunks: "{{ .Values.global.company.name }}-loki-{{ .Values.global.env.short_name }}"
              ruler: "{{ .Values.global.company.name }}-loki-{{ .Values.global.env.short_name }}"
            object_store:
              type: "{{ .Values.global.env.cloud.buckets.type }}"
              gcs:
                bucket_name: "{{ .Values.global.company.name }}-loki-{{ .Values.global.env.short_name }}"
          schemaConfig:
            configs:
              - from: 2025-05-01
                object_store: "{{ .Values.global.env.cloud.buckets.type }}"
                store: tsdb
                schema: v13
                index:
                  prefix: index_
                  period: 24h

  gl-runner:
    enabled: false
  gl-runner-app:
    enabled: false
    chart: "{{ .Values.repository.paths.charts }}/gl-runner"
    values: |
      gl-runner:
        runners:
          secret: "runner-app"
          serviceAccount: "runner-app"
