labels: {}

global:
  company:
    name: #example
    teams:
      domain: ""
      admin:
        emails: []
      qa:
        emails: []
      dev:
        emails: []
      pm:
        emails: []
    domain:
      root: #example.com
      env: #int.example.com, dev.example.com, prd.example.com etc
  network:
    int_nat_gw:
  registry:
    url:
  bucket:
    type:
    prefix:
    suffix:
  env:
    name: #aws-prd or aws-int or aws-stg
    server: #https://2.2.2.2
    short_name: #pre/prd/int/dev/etc
  pomerium:
    policy:
      default: |
        {{- $teams  := .Values.global.company.teams }}
        {{- $emails := .Values.global.access.emails }}
        {{- range $team := .Values.global.access.teams }}
        {{- $emails = concat $emails (get $teams $team).emails }}
        {{- end }}
        allow:
          or:
            {{- range $email :=  $emails }}
            - email:
                is: {{ $email }}
            {{- end }}


externalEnvDomains: []

repository:
  url: #git@github.com:ggramal/infrared.git
  paths:
    charts: argocd/charts/infra/charts
    crds: argocd/charts/infra/crds
    manifests: "argocd/environments/{{ .Values.global.env.name }}/manifests"
    app_charts: argocd/charts/app
    env_from_charts: ../../../../environments/{{ .Values.global.env.name }}
    env_from_app_charts: ../../../environments/{{ .Values.global.env.name }}
  revision: master


manifests:
  enabled: false
  directory: {}
  revision:
  labels: {}
  finalizers: {}
  syncPolicy: {}

crds:
  enabled: false
  operators: {}
#    argocd:
#      enabled: true
#    grafana-operator:
#      enabled: true
#    prometheus-operator:
#      enabled: true
#    cert-manager:
#      enabled: true
#      directory:
#        recurse: true
#    external-dns:
#      enabled: true
#      revision: test
#    konghq:
#      enabled: true
#    postgres-operator:
#      enabled: true
#    redis-operator:
#      enabled: true
#    rabbitmq-cluster:
#      enabled: true
#    rabbitmq-messaging-topology:
#      enabled: true

  labels: {}
  finalizers: {}
  syncPolicy: {}

chart_apps:
  rabbitmq:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  redis:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  external-dns:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  gha-runner:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  gha-operator:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  pomerium:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  postgres:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  grafana:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  konghq:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  cert-manager:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  argocd:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
        environment: {{ .Values.global.env | toYaml | nindent 6 }}
      argocd:
        externalRedis:
          host: rfrm-argocd-{{ .Values.global.env.name }}-redis
          port: 6379
          existingSecret: "argocd-redis"
  prometheus:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
  thanos:
    enabled: false
    values: |
      global: {{ .Values.global | toYaml | nindent 4 }}
