labels: {}

company:
  name: #example
  domain:
    root: #example.com
    env: #int.example.com, dev.example.com, prd.example.com etc

network:
  int_nat_gw:

registry:
  url:

bucket:
  prefix:
  suffix:

externalEnvDomains: []

env:
  name: #aws-prd or aws-int or aws-stg
  server: #https://2.2.2.2
  short_name: #pre/prd/int/dev/etc

repository:
  url: #git@github.com:ggramal/infrared.git
  paths:
    charts: argocd/charts/infra/charts
    crds: argocd/charts/infra/crds
    manifests: "argocd/environments/{{ .Values.env.name }}/manifests"
    app_charts: argocd/charts/app
    env_from_charts: ../../../../environments/{{ .Values.env.name }}
    env_from_app_charts: ../../../environments/{{ .Values.env.name }}
  revision: master


manifests:
  enabled: false
  directory: {}
  revision:
  labels: {}
  finalizers: {}
  syncPolicy: {}

crds:
  enabled: false
  operators: {}
#    argocd:
#      enabled: true
#    grafana-operator:
#      enabled: true
#    prometheus-operator:
#      enabled: true
#    cert-manager:
#      enabled: true
#      directory:
#        recurse: true
#    external-dns:
#      enabled: true
#      revision: test
#    konghq:
#      enabled: true
#    postgres-operator:
#      enabled: true
#    redis-operator:
#      enabled: true
#    rabbitmq-cluster:
#      enabled: true
#    rabbitmq-messaging-topology:
#      enabled: true

  labels: {}
  finalizers: {}
  syncPolicy: {}

chart_apps:
  pomerium:
    enabled: false
    values: |
      global:
        company: {{ .Values.company | toYaml | nindent 6 }}
        registry: {{ .Values.registry | toYaml | nindent 6 }}
        bucket: {{ .Values.bucket | toYaml | nindent 6 }}
        network: {{ .Values.network | toYaml | nindent 6 }}
        env: {{ .Values.env | toYaml | nindent 6 }}
  postgres:
    enabled: false
    values: |
      global:
        company: {{ .Values.company | toYaml | nindent 6 }}
        registry: {{ .Values.registry | toYaml | nindent 6 }}
        bucket: {{ .Values.bucket | toYaml | nindent 6 }}
        network: {{ .Values.network | toYaml | nindent 6 }}
        env: {{ .Values.env | toYaml | nindent 6 }}
  grafana:
    enabled: false
    values: |
      global:
        company: {{ .Values.company | toYaml | nindent 6 }}
        registry: {{ .Values.registry | toYaml | nindent 6 }}
        bucket: {{ .Values.bucket | toYaml | nindent 6 }}
        network: {{ .Values.network | toYaml | nindent 6 }}
        env: {{ .Values.env | toYaml | nindent 6 }}
  konghq:
    enabled: false
    values: |
      global:
        company: {{ .Values.company | toYaml | nindent 6 }}
        registry: {{ .Values.registry | toYaml | nindent 6 }}
        bucket: {{ .Values.bucket | toYaml | nindent 6 }}
        network: {{ .Values.network | toYaml | nindent 6 }}
        env: {{ .Values.env | toYaml | nindent 6 }}
      kong:
        proxy:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: "*.{{ .Values.company.domain.env }}."
  cert-manager:
    enabled: false
    values: |
      global:
        company: {{ .Values.company | toYaml | nindent 6 }}
        registry: {{ .Values.registry | toYaml | nindent 6 }}
        bucket: {{ .Values.bucket | toYaml | nindent 6 }}
        network: {{ .Values.network | toYaml | nindent 6 }}
        env: {{ .Values.env | toYaml | nindent 6 }}
  argocd:
    enabled: false
    values: |
      global:
        company: {{ .Values.company | toYaml | nindent 6 }}
        registry: {{ .Values.registry | toYaml | nindent 6 }}
        bucket: {{ .Values.bucket | toYaml | nindent 6 }}
        network: {{ .Values.network | toYaml | nindent 6 }}
        environment: {{ .Values.env | toYaml | nindent 6 }}
      argo-cd:
        externalRedis:
          host: rfrm-argocd-{{ .Values.env.name }}-redis
          port: 6379
          existingSecret: "argocd-redis"
        server:
          ingress:
            hostname: "argocd.{{ .Values.company.domain.env }}"
  prometheus:
    enabled: false
    values: |
      global:
        company: {{ .Values.company | toYaml | nindent 6 }}
        registry: {{ .Values.registry | toYaml | nindent 6 }}
        bucket: {{ .Values.bucket | toYaml | nindent 6 }}
        network: {{ .Values.network | toYaml | nindent 6 }}
        env: {{ .Values.env | toYaml | nindent 6 }}
  thanos:
    enabled: false
    values: |
      global:
        company: {{ .Values.company | toYaml | nindent 6 }}
        registry: {{ .Values.registry | toYaml | nindent 6 }}
        bucket: {{ .Values.bucket | toYaml | nindent 6 }}
        network: {{ .Values.network | toYaml | nindent 6 }}
        env: {{ .Values.env | toYaml | nindent 6 }}
