{{- with .Values.crds -}}
{{- $name := "crds" -}}
{{- $app_name := (printf "%s-%s" $name $.Values.env.name) }}
{{- if .enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app_name }}
  namespace: argocd
  {{- with .finalizers }}
  finalizers:
  {{- toYaml . | nindent 6 }}
  {{- end }}
  labels:
  {{- with $.Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  destination:
    server: {{ $.Values.env.server }}
    {{- if .namespace }}
    namespace: {{ .namespace }}
    {{- end }}
  project: {{ .project | default "default" }}
  sources:
  {{- range $operator_name, $operator_obj := .operators }}
  {{- if $operator_obj.enabled }}
  - path: {{ printf "%s/%s/%s" $.Values.repository.charts $name $operator_name }}
    {{- with $operator_obj.directory }}
    directory:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    repoURL: {{ $.Values.repository.url }}
    targetRevision: {{ $operator_obj.revision | default $.Values.repository.revision }}
  {{- end }}
  {{- end }}
  {{- with .syncPolicy }}
  syncPolicy:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
