gha-runner:
  enabled: false
  runnerScaleSetName: "infra-runner"
  kubernetesModeServiceAccount:
  controllerServiceAccount:
    namespace: gha-operator
    name: "gha-operator"
  containerMode:
    type: "kubernetes"
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
  listenerTemplate:
    spec:
      containers:
        - name: listener
          resources:
            limits:
              cpu: 300m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
  template:
    spec:
      nodeSelector:
        runner: 'true'
      tolerations:
        - key: runner
          operator: Equal
          value: 'true'
          effect: NoSchedule
      securityContext:
        fsGroup: 1001
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
              value: /home/runner/templates/workflow-pod.yaml
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /home/runner/templates
              name: templates
      volumes:
        - name: templates
          configMap:
            name: workflow-pod
workflowConfigMap:
  enabled: false
  name: workflow-pod
  metaLabels:
    argocd.argoproj.io/instance: "{{ .Release.Name }}"
  spec:
    securityContext:
      fsGroup: 1001
