gha-runner:
  enabled: false
  runnerScaleSetName: "infra-runner"
  kubernetesModeServiceAccount:
  controllerServiceAccount:
    name: "gha-operator"
  containerMode:
    type: "kubernetes"
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
              value: /home/runner/templates/workflow-pod.yaml
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /home/runner/templates
              name: templates
      volumes:
        - name: templates
          configMap:
            name: workflow-pod
workflowConfigMap:
  enabled: false
  name: workflow-pod
