{{- range $serviceAccountName, $serviceAccountObj := .Values.grafanaServiceAccounts }}
{{- if $serviceAccountObj.enabled }}

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  labels:
{{- include "grafana-serviceaccounts.labels" $ | nindent 4 }}
  name: {{ tpl $serviceAccountName $ }}
spec:
  instanceName: {{ tpl (required (printf "grafanaServiceAccounts.%s.instanceName is required" $serviceAccountName) $serviceAccountObj.instanceName) $ }}
  name: {{ tpl ($serviceAccountObj.name | default $serviceAccountName) $ }}
  role: {{ tpl (required (printf "grafanaServiceAccounts.%s.role is required" $serviceAccountName) $serviceAccountObj.role) $ }}
  {{- if hasKey $serviceAccountObj "isDisabled" }}
  isDisabled: {{ $serviceAccountObj.isDisabled }}
  {{- end }}
  {{- with $serviceAccountObj.resyncPeriod }}
  resyncPeriod: {{ tpl . $ }}
  {{- end }}
  {{- if hasKey $serviceAccountObj "suspend" }}
  suspend: {{ $serviceAccountObj.suspend }}
  {{- end }}
  {{- with $serviceAccountObj.tokens }}
  tokens:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}

{{- end }}
{{- end }}
