filters:
#  test:
#    match: kube.*
#    namespace: test
#    filters:
#      mainKube:
#        kubernetes:
#          kubeURL: https://kubernetes.default.svc:443
#          kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#          kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
#      nestKube:
#        nest:
#          operation: lift
#          nestedUnder: kubernetes
#          addPrefix: kubernetes_
#      mainModify:
#        modify:
#          rules:
#          - remove: stream
#          - remove: kubernetes_pod_id
#          - remove: kubernetes_host
#          - remove: kubernetes_container_hash
#      nestAll:
#        nest:
#          operation: nest
#          wildcard:
#          - kubernetes_*
#          nestUnder: kubernetes
#          removePrefix: kubernetes_

clusterFilters:
#  test:
#    match: kube.*
#    namespace: test
#    filters:
#      mainKube:
#        kubernetes:
#          kubeURL: https://kubernetes.default.svc:443
#          kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#          kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
#      nestKube:
#        nest:
#          operation: lift
#          nestedUnder: kubernetes
#          addPrefix: kubernetes_
#      mainModify:
#        modify:
#          rules:
#          - remove: stream
#          - remove: kubernetes_pod_id
#          - remove: kubernetes_host
#          - remove: kubernetes_container_hash
#      nestAll:
#        nest:
#        operation: nest
#        wildcard:
#        - kubernetes_*
#        nestUnder: kubernetes
#        removePrefix: kubernetes_
