inputs:
#  test:
#    enabled: true
#    namespace: test
#    labels:
#      fluentbit: test
#    tail:
#      tag: kube.*
#      path: "/var/log/containers/*.log"
#      readFromHead: false
#      parser: cri
#      refreshIntervalSeconds: 10
#      memBufLimit: 100MB
#      skipLongLines: true
#      skipEmptyLines: true
#      db: /fluent-bit/tail/pos.db
#      dbSync: Normal
#      storageType: memory

#labels:
#  fluentbit1: test

clusterInputs:
#  systemd:
#    enabled: false
#    systemd:
#      tag: systemd.*
#      path: "/var/log/journal"
#      db: "/fluent-bit/tail/systemd.db"
#      dbSync: Normal
#      storageType: memory
#
#  test:
#    labels:
#      fluentbit: test
#    tail:
#      tag: kube.*
#      path: "/var/log/containers/*.log"
#      readFromHead: false
#      parser: cri
#      refreshIntervalSeconds: 10
#      memBufLimit: 100MB
#      skipLongLines: true
#      skipEmptyLines: true
#      db: /fluent-bit/tail/pos.db
#      dbSync: Normal
#      storageType: memory
