inputs:
  enabled: false

outputs:
  enabled: false

filters:
  enabled: false

clusterConfig:
  enabled: false
  configFileFormat: "classic"

config:
  enabled: false
  configFileFormat: "classic"

parsers:
  enabled: false

fluentbit:
  enabled: false
