filters: {}

clusterFilters: {}


inputs: {}

clusterInputs: {}


outputs: {}

clusterOutputs: {}


parsers: {}

clusterParsers: {}


multilineParsers: {}

clusterMultilineParsers: {}


clusterConfig:
  enabled: false
  configFileFormat: "yaml"

config:
  enabled: false
  configFileFormat: "yaml"

fluentbit:
  enabled: false

collector:
  enabled: false

pvs: {}

pvcs: {}
