#labels:
#  fluentbit1: test

filters: {}

clusterFilters: {}


inputs: {}

clusterInputs: {}


outputs: {}

clusterOutputs: {}


parsers: {}

clusterParsers: {}


multilineParsers: {}

clusterMultilineParsers: {}


clusterConfig:
  enabled: false
  configFileFormat: "yaml"
#  labels:
#    fluentbit: test
#  service:
#    parsersFile: /fluent-bit/etc/parsers.conf
#    httpServer: true
#  inputSelector:
#    matchLabels:
#      fluentbit: "test"
#  filterSelector:
#    matchLabels:
#      fluentbit: "test"
#  parserSelector:
#    matchLabels:
#      fluentbit: "test"
#  outputSelector:
#    matchLabels:
#      fluentbit: "test"
#  multilineParserSelector:
#    matchLabels:
#      fluentbit: "test"


config:
  enabled: false
  configFileFormat: "yaml"
#  labels:
#    fluentbit: test
#  service:
#    parsersFile: /fluent-bit/etc/parsers.conf
#    httpServer: true
#  inputSelector:
#    matchLabels:
#      fluentbit: "test"
#  filterSelector:
#    matchLabels:
#      fluentbit: "test"
#  parserSelector:
#    matchLabels:
#      fluentbit: "test"
#  outputSelector:
#    matchLabels:
#      fluentbit: "test"
#  multilineParserSelector:
#    matchLabels:
#      fluentbit: "test"


fluentbit:
  enabled: false

collector:
  enabled: false

pvs: {}

pvcs: {}
