selector: {}

labels: {}

client: {}

config: {}

deployment: {}

podAnnotations: {}

imagePullSecrets: []

serviceAccountName: ""

restartPolicy: ""

podSecurityContext: {}

initContainers: {}

securityContext: {}

imagePullPolicy: IfNotPresent

command: []

args: []

resources: {}

environment: []

ports: []

livenessProbe: {}

readinessProbe: {}

volumeMounts: []

nodeSelector: {}

affinity: {}

tolerations: []

volumes: []

external: {}

ingress: {}

jsonnet: {}

persistentVolumeClaim: {}

route: {}

service: {}

serviceAccount: {}
