{{- if .Values.configs }}
apiVersion: v1
kind: List
items:
{{- range $name, $config := .Values.configs }}
{{- if $config.enabled }}
  - apiVersion: monitoring.coreos.com/v1alpha1
    kind: AlertmanagerConfig
    metadata:
      name: {{ template "alertmanager-configs.fullname" $ }}-{{ $name }}
      labels:
{{ include "alertmanager-configs.labels" $ | indent 8 }}
        {{- toYaml $config.selector | nindent 8 }}
    spec:
      {{- $receivers := list }}
      {{- if kindIs "string" $config.receivers }}
      {{- $receivers = (printf "receivers:\n%s" (tpl $config.receivers $) | fromYaml).receivers }}
      {{- else }}
      {{- $receivers = $config.receivers }}
      {{- end }}
      {{- range $receiver := $receivers }}
      receivers:
        - name: {{ $receiver.name }}
          {{- range $configsName, $configs := omit $receiver "name"}}
          {{ $configsName }}:
          {{- range $config := $configs }}
          {{/* We use ternary operator instead of if/else here because of helm vars scopes */}}
          {{- $config := ternary (tpl (toYaml $config) $ | fromYaml) $config $config.useDefaults }}
          {{- if hasKey $.Values.defaults $configsName }}
          {{- $config := mustMerge $config (get $.Values.defaults $configsName) }}
          {{- end }}
          {{- toYaml (list (omit $config "useDefaults") ) | nindent 10 }}
          {{- end }}
          {{- end }}
      {{- end }}
      {{- with $config.route }}
      route:
      {{- tpl (toYaml $config.route) $ | nindent 8 }}
      {{- end }}
      {{- with $config.inhibitRules }}
      inhibitRules:
      {{- tpl (toYaml $config.inhibitRules) $ | nindent 8 }}
      {{- end }}
      {{- with $config.muteTimeIntervals }}
      muteTimeIntervals:
      {{- tpl (toYaml $config.muteTimeIntervals) $ | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
