{{- if .Values.configs }}
apiVersion: v1
kind: List
items:
{{- range $name, $config := .Values.configs }}
{{- if $config.enabled }}
  - apiVersion: monitoring.coreos.com/v1alpha1
    kind: AlertmanagerConfig
    metadata:
      name: {{ template "alertmanager-configs.fullname" $ }}-{{ $name }}
      labels:
{{ include "alertmanager-configs.labels" $ | indent 8 }}
        {{- toYaml $config.selector | nindent 8 }}
    spec:
      {{- with $config.receivers }}
      receivers:
      {{- toYaml $config.receivers | nindent 8 }}
      {{- end }}
      {{- with $config.route }}
      route:
      {{- tpl (toYaml $config.route) $ | nindent 8 }}
      {{- end }}
      {{- with $config.inhibitRules }}
      inhibitRules:
      {{- tpl (toYaml $config.inhibitRules) $ | nindent 8 }}
      {{- end }}
      {{- with $config.muteTimeIntervals }}
      muteTimeIntervals:
      {{- tpl (toYaml $config.muteTimeIntervals) $ | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
