apiVersion: v2
name: grafana
version: 0.1.0
appVersion: "v9.5"
dependencies:
  - name: grafana-dashboards
    version: 0.1.0
    repository: file://../chart_deps/grafana/dashboards
    alias: dashboard
    condition: dashboard.enabled
  - name: grafana-datasources
    version: 0.1.0
    repository: file://../chart_deps/grafana/datasources
    alias: datasource
    condition: datasource.enabled
  - name: grafana-operated
    version: 0.1.0
    repository: file://../chart_deps/grafana/grafana-operated
    alias: grafana-main
    condition: grafana-main.enabled
  #https://github.com/grafana/grafana-operator/tree/v5.8.1/deploy/helm/grafana-operator
  - name: grafana-operator
    version: v5.8.1
    alias: grafana-operator
    condition: grafana-operator.enabled
    repository: oci://ghcr.io/grafana/helm-charts
