apiVersion: v2
name: external-dns
version: 0.1.0
appVersion: "0.21.0"
description: Chart for configuring and installing external-dns

dependencies:
  - name: core
    version: 0.1.0
    repository: file://../chart_deps/app/core
  - name: prometheus-lib
    version: 0.1.0
    repository: file://../chart_deps/prometheus/lib
