external-dns:
  enabled: false
  # Overrides kept in the same layout as the upstream external-dns chart.
  image:
    repository: registry.k8s.io/external-dns/external-dns
    tag: v0.21.0
  args:
    - '--provider={{ include "external-dns.providerName" . }}'
    - --policy=upsert-only
    - --registry=txt
    - --interval=1m
    - --log-level=info
    - --log-format=json
    - --source=service
    - --source=ingress
    - --no-expose-internal-ipv6
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 10m
      memory: 35Mi
  serviceAccount:
    create: false
    name: external-dns
  podSecurityContext:
    fsGroup: 1001
    fsGroupChangePolicy: Always
  legacySecurityContext: true
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    privileged: false
    readOnlyRootFilesystem: true
    runAsGroup: 1001
    runAsNonRoot: true
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault
  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 2
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
