apiVersion: v2
name: vedro
description: Vedro controller and cloud resource stack
type: application
version: 0.1.0
dependencies:
  - name: vedro-controller
    version: 0.1.0
    repository: file://../chart_deps/vedro/vedro-controller
    alias: vedro-controller
    condition: vedro-controller.enabled
  - name: vedro-resources
    version: 0.1.0
    repository: file://../chart_deps/vedro/vedro-resources
    alias: vedro-resources
    condition: vedro-resources.enabled
