vedro-controller:
  enabled: false
  controller:
    probes:
      enabled: false
    prometheus-rules:
      enabled: false

vedro-resources:
  enabled: false
  providers: {}
  principals: {}
  buckets: {}
