global:
  company:
    name: #example
    teams:
      domain: ""
      admin:
        emails: []
      qa:
        emails: []
      dev:
        emails: []
      pm:
        emails: []
    domain:
      root: #example.com
      env: #int.example.com, dev.example.com, prd.example.com etc
  cloud:
    type: ""
  network:
    int_nat_gw:
  registry:
    url:
  bucket:
    type:
    prefix:
    suffix:
  #Cant use env: here because
  #env is already set as global
  #attr in original argocd chart
  env:
    name: #aws-prd or aws-int or aws-stg
    server: #https://2.2.2.2
    short_name: #pre/prd/int/dev/etc
  ingress:
    class: pomerium
  access:
    teams: ["admin"]
    emails: []
  alerts: {}
  pomerium:
    policy:
      default: |
        {{- $teams  := .Values.global.company.teams }}
        {{- $emails := .Values.global.access.emails }}
        {{- range $team := .Values.global.access.teams }}
        {{- $emails = concat $emails (get $teams $team).emails }}
        {{- end }}
        allow:
          or:
            {{- range $email :=  $emails }}
            - email:
                is: {{ $email }}
            {{- end }}
