global:
  company:
    name: #example
    domain: #example.com
  repo:
    type:
    provider:
    group:
    name:
    revision:
  envs: {}
  #Cant use env: here because
  #env is already set as global
  #attr in original argocd chart
  env:
    name: #aws-prd or aws-int or aws-stg
    cloud_short_name: #gcp-prd, gcp-int, etc; stable infrastructure identifier
    server: #https://2.2.2.2
    short_name: #gcp-pre/gcp-prd/gcp-int/etc
    users: {}
    dns:
      root:
      domain:
      provider:
    cloud:
      name: ""
  ingress:
    class: pomerium
  access:
    roles: ["admin"]
  alerts: {}
  pomerium:
    policy:
      default: |
        {{- $emails := list }}
        {{- $domains := list }}
        {{- $roles := .Values.global.access.roles }}
        {{- range $user := .Values.global.env.users }}
        {{- range $role := $user.roles }}
        {{- if has $role $roles }}
        {{- if hasPrefix "*@" $user.name }}
        {{- $domains = append $domains (trimPrefix "*@" $user.name) }}
        {{- else }}
        {{- $emails = append $emails $user.name }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- $emails = uniq $emails }}
        {{- $domains = uniq $domains }}
        allow:
          or:
            {{- range $email :=  $emails }}
            - email:
                is: {{ $email }}
            {{- end }}
            {{- range $domain := $domains }}
            - domain:
                is: {{ $domain }}
            {{- end }}
