PrometheusAlerts: {}
#  api:
#    env: "{{ .Values.global.env.short_name }}"
#    team: sre
#    selector:
#      prometheus: main
#    AbsentMetricCritical:
#      enabled: false
#      rules:
#        probe_success:
#          enabled: false
#          source: '{{ .Values.global.app.name }}-api probes'
#          query: '{instance="https://api.{{ .Values.global.app.name }}.{{ .Values.global.env.dns.domain }}/api/health/db"}'

PrometheusRules: {}
#  - name: chicken
#    namespace: default
#    selector:
#      prometheus: chicken-сoop-1
#    groups:
#      - name: chicken-coop-1
#        rules:
#          - alert: chickens-not-good
#            annotations:
#              what: chicken butt
#              who: chicken poo
#            expr: name:chicken_not_ok:percent != 1
#            for: 2m
#            labels:
#              env: kitchen
#              severity: ACHTUNG
#              team: KFC
#          - record: name:chicken_not_ok:percent
#            expr: ((sum (chicken_not_ok)/chickens) * 100)
