kong-plugins:
  enabled: false

thanos:
  enabled: false
  existingObjstoreSecret: ""
  query:
    enabled: false
  queryFrontend:
    enabled: false
  bucketweb:
    enabled: false
  compactor:
    enabled: false
    serviceAccount:
      create: false
      name: thanos
  storegateway:
    enabled: false
    serviceAccount:
      create: false
      name: thanos
  ruler:
    enabled: false
  recieve:
    enabled: false
  receiveDistributor:
    enabled: false
  metrics:
    enabled: false
  volumePermissions:
    enabled: false
  minio:
    enabled: false
  networkPolicy:
    enabled: false
