global:
  company:
    name: #example
    domain:
      root: #example.com
      env: #int.example.com, dev.example.com, prd.example.com etc
  network:
    int_nat_gw:
  registry:
    url:
  bucket:
    prefix:
    suffix:
  env:
    name: #aws-prd or aws-int or aws-stg
    server: #https://2.2.2.2
    short_name: #pre/prd/int/dev/etc

kong-plugins:
  enabled: false

thanos:
  enabled: false
  existingObjstoreSecret: ""
  query:
    enabled: false
  queryFrontend:
    enabled: false
  bucketweb:
    enabled: false
  compactor:
    enabled: false
    serviceAccount:
      create: false
      name: thanos
  storegateway:
    enabled: false
    serviceAccount:
      create: false
      name: thanos
  ruler:
    enabled: false
  recieve:
    enabled: false
  receiveDistributor:
    enabled: false
  metrics:
    enabled: false
  volumePermissions:
    enabled: false
  minio:
    enabled: false
  networkPolicy:
    enabled: false
