global:
  company:
    name: #example
    teams:
      domain: ""
      admin:
        emails: []
      qa:
        emails: []
      dev:
        emails: []
      pm:
        emails: []
    domain:
      root: #example.com
      env: #int.example.com, dev.example.com, prd.example.com etc
  network:
    int_nat_gw:
  registry:
    url:
  bucket:
    type:
    prefix:
    suffix:
  ingress:
    class: pomerium
  env:
    name: #aws-prd or aws-int or aws-stg
    server: #https://2.2.2.2
    short_name: #pre/prd/int/dev/etc
  access:
    teams: ["admin"]
    emails: []
  pomerium:
    policy:
      default: ""

ingresses:
  query:
    enabled: false
    name: '{{ include "thanos.fullname" . }}-query'
    service:
      name: '{{ include "thanos.fullname" . }}-query'
      port: 9090
    className: "{{ .Values.global.ingress.class }}"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-pomerium
      ingress.pomerium.io/policy: |
        {{- tpl .Values.global.pomerium.policy.default $ | indent 2}}
    hosts:
      - host: "tq.{{ .Values.global.company.domain.env }}"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: tq-tls
        hosts:
          - "tq.{{ .Values.global.company.domain.env }}"
  storegateway:
    enabled: false
    name: '{{ include "thanos.fullname" . }}-storegateway-grpc'
    service:
      name: '{{ include "thanos.fullname" . }}-storegateway'
      port: 10901
    className: konghq
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-konghq
      konghq.com/protocols: grpc,grpcs
      konghq.com/plugins: thanos-store-main-ip-restriction
    hosts:
      - host: "thanos-store.{{ .Values.global.company.domain.env }}"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: thanos-store-tls
        hosts:
          - "thanos-store.{{ .Values.global.company.domain.env }}"


kong-plugins:
  enabled: false
  plugins:
    - name: thanos-store-main-ip-restriction
      plugin_name: ip-restriction
      annotations:
        kubernetes.io/ingress.class: konghq
      config:
        allow:
          - "{{ .Values.global.network.int_nat_gw }}"

thanos:
  enabled: false
  existingObjstoreSecret: "thanos"
  query:
    enabled: false
    dnsDiscovery:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 2000m
        memory: 2Gi
  queryFrontend:
    enabled: false
  bucketweb:
    enabled: false
  compactor:
    enabled: false
    persistence:
      size: 15Gi
    resources:
      requests:
        cpu: 20m
        memory: 45Mi
      limits:
        cpu: 1500m
        memory: 1Gi
    serviceAccount:
      create: false
      name: thanos
  storegateway:
    enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    service:
      annotations:
        konghq.com/protocol: grpc
    serviceAccount:
      create: false
      name: thanos
  ruler:
    enabled: false
  recieve:
    enabled: false
  receiveDistributor:
    enabled: false
  metrics:
    enabled: false
  volumePermissions:
    enabled: false
  minio:
    enabled: false
  networkPolicy:
    enabled: false
