argo-cd:
  enabled: false
  crds:
    install: false

  configs:
    cm:
      create: true
    params:
      server.insecure: true

  redis:
    enabled: false

  redis-ha:
    enabled: false
    hardAntiAffinity: false
    haproxy:
      hardAntiAffinity: false

  controller:
    replicas: 1

  server:
    replicas: 2

  repoServer:
    replicas: 2

  applicationSet:
    replicaCount: 2

certificates:
  enabled: false

redis:
  enabled: false
  redisServiceMonitor:
    enabled: false
    prometheusSelector:
      prometheus: main
  sentinelServiceMonitor:
    enabled: false
    prometheusSelector:
      prometheus: main
