apiVersion: v2
name: konghq
version: 1.0.0
appVersion: "3.6"
dependencies:
  - name: kong-plugins
    version: 0.1.0
    repository: file://../chart_deps/konghq/plugins
    alias: kong-plugins
    condition: kong-plugins.enabled
  #https://github.com/Kong/charts/tree/kong-2.37.1/charts/kong
  - name: kong
    version: 2.37.1
    repository: https://charts.konghq.com
