apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- include "prometheus-podmonitor.labels" . | nindent 4 }}
{{- else }}
    {{- include "prometheus-podmonitor.labels" . | nindent 4 }}
{{- end }}
  name: {{ template "prometheus-podmonitor.fullname" . }}
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- end }}
spec:
  {{- with .Values.podMetricsEndpoints }}
  podMetricsEndpoints:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  jobLabel: {{ template "prometheus-podmonitor.fullname" . }}
  {{- if .Values.namespaceSelector }}
  {{- with .Values.namespaceSelector }}
  namespaceSelector:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- else }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
    {{- tpl (toYaml .Values.selector) . | nindent 6 }}
{{- if .Values.targetLabels }}
  targetLabels:
{{- range .Values.targetLabels }}
  - {{ . }}
{{- end }}
{{- end }}
