apiVersion: v2
name: gke-resources
version: 0.1.0
dependencies:
  - name:
    version: 0.1.0
    repository: file://../chart_deps/gcp/compute-class
    alias: computeClass
    condition: computeClass.enabled
