{{- $clConfig :=  .Values.clusterConfig }}
{{- $labels := include "fluentbit-operated.labels" $ | fromYaml }}
{{- $clConfig = set $clConfig "name" (include "fluentbit-operated.fullname" . ) }}
{{- include "fluentbit.clusterconfig" (list $ $labels $clConfig ) }}
