{{- $config :=  .Values.config }}
{{- $labels := include "fluentbit-operated.labels" $ | fromYaml }}
{{- $config = set $config "name" ( include "fluentbit-operated.fullname" . ) }}
{{- include "fluentbit.config" (list $ $labels $config ) }}
