apiVersion: v2
name: grafana
version: 0.1.0
appVersion: "v12.1.1"
dependencies:
  - name: grafana-dashboards
    version: 0.1.0
    repository: file://../chart_deps/grafana/dashboards
    alias: dashboard
    condition: dashboard.enabled
  - name: grafana-datasources
    version: 0.1.0
    repository: file://../chart_deps/grafana/datasources
    alias: datasource
    condition: datasource.enabled
  - name: grafana-operated
    version: 0.1.0
    repository: file://../chart_deps/grafana/grafana-operated
    alias: grafana-main
    condition: grafana-main.enabled
  #https://github.com/grafana/grafana-operator/tree/master/deploy/helm/grafana-operator
  - name: grafana-operator
    version: v5.19.4
    alias: grafana-operator
    condition: grafana-operator.enabled
    repository: oci://ghcr.io/grafana/helm-charts
  - name: core
    version: 0.1.0
    repository: file://../chart_deps/app/core
  - name: fluentbit-operated
    repository: file://../chart_deps/fluent/fluentbit/fluentbit-operated/
    version: 0.1.0
    alias: fluentbit-filters
    condition: fluentbit-filters.enabled
