apiVersion: v2
name: grafana
version: 0.1.0
appVersion: "v11.6.0"
dependencies:
  - name: grafana-dashboards
    version: 0.1.0
    repository: file://../chart_deps/grafana/dashboards
    alias: common-google-cloud-dashboard
    condition: common-google-cloud-dashboard.enabled
  - name: grafana-dashboards
    version: 0.1.0
    repository: file://../chart_deps/grafana/dashboards
    alias: dashboard
    condition: dashboard.enabled
  - name: grafana-dashboards
    version: 0.1.0
    repository: file://../chart_deps/grafana/dashboards
    alias: common-dashboard
    condition: common-dashboard.enabled
  - name: grafana-datasources
    version: 0.1.0
    repository: file://../chart_deps/grafana/datasources
    alias: datasource
    condition: datasource.enabled
  - name: grafana-operated
    version: 0.1.0
    repository: file://../chart_deps/grafana/grafana-operated
    alias: grafana-main
    condition: grafana-main.enabled
  #https://github.com/grafana/grafana-operator/tree/v5.17.0/deploy/helm/grafana-operator
  - name: grafana-operator
    version: v5.17.1
    alias: grafana-operator
    condition: grafana-operator.enabled
    repository: oci://ghcr.io/grafana/helm-charts
  - name: core
    version: 0.1.0
    repository: file://../chart_deps/app/core
