{{- if .Values.enabled }}
{{- $labels := include "external-dns.labels" . | fromYaml -}}
{{- $serviceAccount := mustDeepCopy .Values.serviceAccount -}}
{{- $serviceAccount = set $serviceAccount "name" (include "external-dns.serviceAccountName" .) -}}
{{- include "core.serviceAccount" (list . $labels $serviceAccount) -}}
{{- end }}
