{{- if and .Values.enabled .Values.serviceMonitor.enabled -}}
{{- $labels := include "external-dns.labels" . | fromYaml -}}
{{- $monitor := tpl (toYaml .Values.serviceMonitor) . | fromYaml -}}
{{- $monitor = set $monitor "name" (include "external-dns.fullname" .) -}}
{{- $monitor = set $monitor "jobLabel" "app.kubernetes.io/instance" -}}
{{- $monitor = set $monitor "selectorLabels" (include "external-dns.selectorLabels" . | fromYaml) -}}
{{- $workloadNamespace := .Values.namespaceOverride | default .Release.Namespace -}}
{{- $monitorNamespace := .Values.serviceMonitor.namespace | default $workloadNamespace -}}
{{- $monitor = set $monitor "namespace" $monitorNamespace -}}
{{- $monitor = set $monitor "namespaceSelector" ($monitor.namespaceSelector | default $workloadNamespace) -}}
{{- include "prometheus.serviceMonitor" (list . $labels $monitor) -}}
{{- end -}}
