global:
  image:
    tag: 2.9.0
  company:
    name: #example
    admins:
      domain: ""
      emails: []
    domain:
      root: #example.com
      env: #int.example.com, dev.example.com, prd.example.com etc
  network:
    int_nat_gw:
  registry:
    url:
  bucket:
    type:
    prefix:
    suffix:
  ingress:
    class: pomerium
  env:
    name: #aws-prd or aws-int or aws-stg
    server: #https://2.2.2.2
    short_name: #pre/prd/int/dev/etc

node-1:
  enabled: false
node-2:
  enabled: false
node-3:
  enabled: false
node-4:
  enabled: false
node-5:
  enabled: false
node-6:
  enabled: false
node-7:
  enabled: false
node-8:
  enabled: false

postgres-cluster:
  enabled: false
  podMonitor:
    enabled: false
    prometheusSelector:
      prometheus: main
