{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
{{- if .Values.serviceMonitor.labels }}
  labels:
    {{- include "prometheus-postgres-exporter.labels" . | nindent 4 }}
{{ toYaml .Values.serviceMonitor.labels | indent 4}}
{{- end }}
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
{{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
{{- end }}
spec:
  endpoints:
{{- range $endpoint :=  .Values.serviceMonitor.endpoints }}
  - targetPort: {{ $.Values.service.name }}
{{- if $endpoint.interval }}
    interval: {{ $endpoint.interval }}
{{- end }}
{{- if $endpoint.path }}
    path: {{ $endpoint.path }}
{{- end }}
{{- if $endpoint.timeout }}
    scrapeTimeout: {{ $endpoint.timeout }}
{{- end }}
{{- if $endpoint.params }}
    params:
{{- toYaml $endpoint.params | nindent 6 }}
{{- end }}
{{- if $endpoint.metricRelabelings }}
    metricRelabelings:
{{ toYaml $endpoint.metricRelabelings | indent 4 }}
{{- end }}
{{- if $endpoint.relabelings }}
    relabelings:
{{ toYaml $endpoint.relabelings | nindent 4 }}
{{- end }}
{{- end }}
  jobLabel: {{ template "prometheus-postgres-exporter.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "prometheus-postgres-exporter.selectorLabels" . | nindent 6 }}
{{- if .Values.serviceMonitor.targetLabels }}
  targetLabels:
{{- range .Values.serviceMonitor.targetLabels }}
  - {{ . }}
{{- end }}
{{- end }}
{{- end }}
