{{- $labels := include "external-dns.labels" . | fromYaml -}}
{{- $clusterRole := dict "enabled" .Values.rbac.create "name" (include "external-dns.fullname" .) -}}
{{- $clusterRole = set $clusterRole "rules" (mustDeepCopy .Values.rbac.rules) -}}
{{- if .Values.rbac.additionalPermissions }}
{{- $clusterRole = set $clusterRole "rules" (concat $clusterRole.rules .Values.rbac.additionalPermissions) -}}
{{- end -}}
{{- $clusterRole = set $clusterRole "serviceAccount" (dict "name" (include "external-dns.serviceAccountName" .)) -}}
{{- include "core.clusterrole" (list . $labels $clusterRole) -}}
