redis-operator:
  enabled: false
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
  issuer:
    create: false
  certmanager:
    enabled: false

redis-sentinel:
  enabled: false
  redisSentinel:
    name: ""
    #tag: v7.0.15
  serviceMonitor:
    enabled: true
    extraLabels:
      prometheus: main
  redisExporter:
    enabled: true

redis-replication:
  enabled: false
  redisReplication:
    name: ""
    clusterSize: 3
    #tag: v7.0.15
    resources: {}
  externalService:
    enabled: true
  serviceMonitor:
    enabled: true
    extraLabels:
      prometheus: main
  redisExporter:
    enabled: true
  sentinel:
    enabled: false
