apiVersion: v2
name: postgres
version: 0.1.0
dependencies:
  - name: postgres-cluster
    version: 0.1.0
    repository: file://../chart_deps/postgres/postgres-cluster
    alias: postgres-main
    condition: postgres-main.enabled
  #https://github.com/zalando/postgres-operator/tree/v1.14.0/charts/postgres-operator
  - name: postgres-operator
    version: v1.14.0
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    alias: postgres-operator
    condition: postgres-operator.enabled
  - name: common
    version: 0.1.0
    repository: file://../chart_deps/app/common/
    alias: pgadmin
    condition: pgadmin.enabled
