{{- range $ingress_name, $ingress_obj := .Values.ingresses }}
{{- $labels := include "rabbitmq.labels" $ | fromYaml }}
{{- $labels := set $labels "app.kubernetes.io/component"  $ingress_name }}
{{- include "core.ingress" (list $ $labels $ingress_obj )}}
{{- end }}
