global:
  company:
    name: #example
    domain:
      root: #example.com
      env: #int.example.com, dev.example.com, prd.example.com etc
  network:
    int_nat_gw:
  registry:
    url:
  bucket:
    prefix:
    suffix:
  env:
    name: #aws-prd or aws-int or aws-stg
    server: #https://2.2.2.2
    short_name: #pre/prd/int/dev/etc

certificates:
  enabled: false

cert-manager:
  enabled: false
  cainjector:
    enabled: true
