{{- $redisExporterDefaults := include "redis-operated.redisExporterDefaults" . | fromYaml }}
{{- $redisExporter := merge .Values.redis.exporter $redisExporterDefaults }}
{{- $redis := .Values.redis }}
{{- $redis := unset $redis "exporter" }}
{{- $redis := set $redis "exporter" $redisExporter }}
{{- $sentinelExporterDefaults := include "sentinel-operated.sentinelExporterDefaults" . | fromYaml }}
{{- $sentinelExporter := merge .Values.sentinel.exporter $sentinelExporterDefaults }}
{{- $sentinel := .Values.sentinel }}
{{- $sentinel := unset $sentinel "exporter" }}
{{- $sentinel := set $sentinel "exporter" $sentinelExporter }}
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: {{ include "redis-operated.fullname" . }}
  labels:
{{- include "redis-operated.labels" . | nindent 4 }}
spec:
  {{- with $sentinel }}
  sentinel:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $redis }}
  redis:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.auth }}
  auth:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.bootstrapNode }}
  bootstrapNode:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.labelWhitelist }}
  labelWhitelist:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}

