{{- $serviceMonitor :=  deepCopy (.Values.redis.monitor | default dict) }}
{{- $labels := include "redis-operated.labels" $ | fromYaml }}
{{- if not (hasKey $serviceMonitor "name") }}
{{- $serviceMonitor = set $serviceMonitor "name" (include "redis-operated.clusterName" . ) }}
{{- end }}
{{- if not (hasKey $serviceMonitor "jobLabel") }}
{{- $serviceMonitor = set $serviceMonitor "jobLabel" (include "redis-operated.clusterName" . ) }}
{{- end }}
{{- include "prometheus.serviceMonitor" (list $ $labels $serviceMonitor ) }}
