{{- if .Values.redisServiceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "redis-operated.fullname" . }}-redis
  labels:
{{- if .Values.redisServiceMonitor.labels }}
    {{ toYaml .Values.redisServiceMonitor.labels | indent 4 }}
    {{- include "redis-operated.labels" . | nindent 4 }}
    {{- if .Values.redisServiceMonitor.prometheusSelector }}
    {{ tpl (toYaml .Values.redisServiceMonitor.prometheusSelector) . | nindent 4}}
    {{- end }}
{{- else }}
    {{- if .Values.redisServiceMonitor.prometheusSelector }}
    {{ tpl (toYaml .Values.redisServiceMonitor.prometheusSelector) . | nindent 4}}
    {{- end }}
    {{- include "redis-operated.labels" . | nindent 4 }}
{{- end }}
spec:
  {{- with .Values.redisServiceMonitor.endpoints }}
  endpoints:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
    {{- include "redis-operated.serviceSelectorLabels" . | nindent 6 }}
{{- if .Values.redisServiceMonitor.targetLabels }}
  targetLabels:
{{- range .Values.redisServiceMonitor.targetLabels }}
  - {{ . }}
{{- end }}
{{- end }}
{{- end }}
