{{- $sentinel := .Values.sentinel | default dict }}
{{- if $sentinel.enabled }}
{{- $serviceMonitor :=  deepCopy ($sentinel.monitor | default dict) }}
{{- $labels := include "redis-operated.labels" $ | fromYaml }}
{{- if not (hasKey $serviceMonitor "name") }}
{{- $serviceMonitor = set $serviceMonitor "name" (include "redis-operated.sentinelName" . ) }}
{{- end }}
{{- if not (hasKey $serviceMonitor "jobLabel") }}
{{- $serviceMonitor = set $serviceMonitor "jobLabel" (include "redis-operated.sentinelName" . ) }}
{{- end }}
{{- include "prometheus.serviceMonitor" (list $ $labels $serviceMonitor ) }}
{{- end }}
