apiVersion: v2
name: redis
version: 0.1.0
dependencies:
  # all charts https://github.com/OT-CONTAINER-KIT/redis-operator/tree/main/charts
  # all versions https://github.com/OT-CONTAINER-KIT/helm-charts
  - name: redis-operator
    version: 0.24.0
    alias: redis-operator
    repository: https://ot-container-kit.github.io/helm-charts
    condition: redis-operator.enabled
  - name: redis-sentinel
    version: 0.16.12
    repository: https://ot-container-kit.github.io/helm-charts
    alias: redis-sentinel
    condition: redis-sentinel.enabled
  - name: redis-replication
    version: 0.17.0
    repository: https://ot-container-kit.github.io/helm-charts
    alias: redis-replication
    condition: redis-replication.enabled
