apiVersion: v2
name: redis
version: 0.1.0
dependencies:
  # all charts https://github.com/OT-CONTAINER-KIT/redis-operator/tree/main/charts
  # all versions https://github.com/OT-CONTAINER-KIT/helm-charts
  - name: redis-operator
    version: 0.24.0
    alias: redis-operator
    repository: https://ot-container-kit.github.io/helm-charts
    condition: redis-operator.enabled
  - name: redis-operated
    version: 0.1.0
    repository: file://../chart_deps/redis/redis-operated
    alias: redis-operated
    condition: redis-operated.enabled
  - name: prometheus-lib
    version: 0.1.0
    repository: file://../chart_deps/prometheus/lib
