global:
  company:
    name: #example
    admins:
      domain: ""
      emails: []
    domain:
      root: #example.com
      env: #int.example.com, dev.example.com, prd.example.com etc
  network:
    int_nat_gw:
  registry:
    url:
  bucket:
    type:
    prefix:
    suffix:
  ingress:
    class: pomerium
  env:
    name: #aws-prd or aws-int or aws-stg
    server: #https://2.2.2.2
    short_name: #pre/prd/int/dev/etc

redis-operator:
  enabled: false
  image:
    tag: v1.3.0-rc1@sha256:bc30bff00e8ed1394f4bf8c6745ef04cdd520c44fbfc349faad40d1c5f7b9725
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 350m
      memory: 100Mi
  monitoring:
    enabled: true
    serviceMonitor: true
    prometheus:
      name: main

redis-main:
  enabled: false
  sentinelServiceMonitor:
    enabled: true
    prometheusSelector:
      prometheus: main
  sentinel:
    exporter:
      enabled: true
  redisServiceMonitor:
    enabled: true
    prometheusSelector:
      prometheus: main
  redis:
    exporter:
      enabled: true
########################
# Redis example config
########################
#  redis-main:
#    auth:
#      secretPath: redis
#    sentinel:
#      replicas: 3
#      resources:
#        requests:
#          cpu: 10m
#          memory: 10Mi
#        limits:
#          memory: 200Mi
#          cpu: 1000m
#      exporter:
#        enabled: true
#        image: leominov/redis_sentinel_exporter:1.7.1
#        resources:
#          requests:
#            cpu: 10m
#            memory: 10Mi
#          limits:
#            cpu: 100m
#            memory: 50Mi
#    redis:
#      replicas: 3
#      resources:
#        requests:
#          cpu: 50m
#          memory: 10Mi
#        limits:
#          cpu: 1100m
#          memory: 250Mi
