redis-operator:
  enabled: false
  redisOperator:
    name: ""
  resources:
    requests:
      cpu: 20m
      memory: 30Mi
    limits:
      cpu: 350m
      memory: 300Mi
  issuer:
    create: false
  certmanager:
    enabled: false

redis-sentinel:
  enabled: false
  redisSentinel:
    name: ""
    image: quay.io/opstree/redis-sentinel
    tag: v8.6.1
    resources:
      requests:
        cpu: 50m
        memory: 10Mi
      limits:
        memory: 500Mi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter
    tag: "v1.83.0"
  serviceMonitor:
    enabled: true
    extraLabels:
      prometheus: main
  redisSentinelConfig:
    redisReplicationName: ""
    quorum: '2'
    redisPort: '6379'

redis-replication:
  enabled: false
  redisReplication:
    name: ""
    clusterSize: 3
    image: quay.io/opstree/redis
    tag: v8.6.1
    resources:
      requests:
        cpu: 50m
        memory: 10Mi
      limits:
        memory: 500Mi
  externalService:
    enabled: false
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter
    tag: "v1.83.0"
  sentinel:
    enabled: false
  serviceMonitor:
    enabled: true
    extraLabels:
      prometheus: main
