name: 'openid_connect'
label: 'Google Login'
args:
  name: 'openid_connect'
  scope: ['openid', 'profile', 'email']
  issuer: 'https://accounts.google.com'
  client_auth_method: 'query'
  uid_field: 'preferred_username'
  pkce: true
  response_type: 'code'
  discovery: true
  client_options:
    identifier: '<client ID>'
    secret: '<Client Secret>'
    redirect_uri: 'https://<Gitlab URL>/users/auth/openid_connect/callback'
