{{- $workflowPodConfig := dict "name" "workflow-pod" }}
{{- $workflowPodConfig = set $workflowPodConfig "data" (dict "workflow-pod.yaml" (include "gha-runner.workflow.podTemplate" . )) }}
{{- $labels := include "gha-runner.labels" . | fromYaml }}
{{- include "core.configMap" (list $ $labels $workflowPodConfig) -}}
