gha-runner-scale-set:
  enabled: false
  containerMode:
    type: "kubernetes"
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
  controllerServiceAccount:
    namespace: gha-operator
    name: "gha-operator"
