apiVersion: v2
name: thanos
description: thanos stack for all environments

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
  #https://github.com/bitnami/charts/tree/4440601576022526f79ff6a465fb49b7466d6d3d/bitnami/thanos
  - name: thanos
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.5.0
    alias: int
    condition: int.enabled
  #https://github.com/bitnami/charts/tree/4440601576022526f79ff6a465fb49b7466d6d3d/bitnami/thanos
  - name: thanos
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.5.0
    alias: prd
    condition: prd.enabled
  #https://github.com/bitnami/charts/tree/20ea1e44daf4da3438fbac5f867030d09868315b/bitnami/thanos
  - name: thanos
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.5.0
    alias: dev
    condition: dev.enabled
