{{- $defaultPodMetricsEndpoints := include "postgres-cluster.defaultPodMetricsEndpoints" . | fromYaml }}
{{/*
If podMetricsEndpoint has the same key as default podMetricsEndpoint
its attrs override the attrs of default one
*/}}
{{- $podMetricsEndpoints := merge .Values.podMonitor.podMetricsEndpoints $defaultPodMetricsEndpoints }}
{{/*
We need to use sortAlpha here so that podMetricsEndpoints will appear
in predictable order. Also sortAlpha cant be used with 'values'
function because it doesnt produce object
*/}}
{{- $podMetricsEndpoints_list := list }}
{{- range $pmeName := (keys $podMetricsEndpoints | sortAlpha) }}
{{- $podMetricsEndpoints_list = append $podMetricsEndpoints_list (get $podMetricsEndpoints $pmeName) }}
{{- end }}
{{- if .Values.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "postgres-cluster.fullname" . }}
  labels:
{{- if .Values.podMonitor.labels }}
{{ toYaml .Values.podMonitor.labels | indent 4 }}
    {{- if .Values.podMonitor.prometheusSelector }}
    {{ tpl (toYaml .Values.podMonitor.prometheusSelector) . | nindent 4}}
    {{- end }}
    {{- include "postgres-cluster.labels" . | nindent 4 }}
{{- else }}
    {{- if .Values.podMonitor.prometheusSelector }}
    {{ tpl (toYaml .Values.podMonitor.prometheusSelector) . | nindent 4}}
    {{- end }}
    {{- include "postgres-cluster.labels" . | nindent 4 }}
{{- end }}
spec:
  {{- with $podMetricsEndpoints_list }}
  podMetricsEndpoints:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  jobLabel: {{ template "postgres-cluster.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "postgres-cluster.podSelectorLabels" . | nindent 6 }}
{{- if .Values.podMonitor.podTargetLabels }}
  podTargetLabels:
{{- range .Values.podMonitor.podTargetLabels }}
  - {{ . }}
{{- end }}
{{- end }}
{{- end }}
