{{- range $name, $multilineParser :=  .Values.multilineParsers }}
{{- $labels := include "fluentbit-parsers.labels" $ | fromYaml }}
{{- $multilineParser = set $multilineParser "name" ( printf "%s-%s" (include "fluentbit-parsers.fullname" $ )  $name ) }}
{{- if eq (hasKey $multilineParser "namespace") false }}
{{- $multilineParser = set $multilineParser "namespace" $.Release.Namespace }}
{{- end }}
{{- if eq (hasKey $multilineParser "enabled") false }}
{{- $multilineParser = set $multilineParser "enabled" true }}
{{- end }}
{{- if $multilineParser.labels }}
{{- $labels = merge $labels $multilineParser.labels }}
{{- end }}
{{- if $.Values.labels }}
{{- $labels = merge $labels $.Values.labels }}
{{- end }}
{{- include "fluentbit.multilineparser" (list $ (toYaml $labels) $multilineParser ) }}
{{- end }}
