labels: {}

company:
  name: #example
  admins:
    domain: ""
    emails: []
  domain:
    root: #example.com

network:
  int_nat_gw:

bucket:
  prefix:
  suffix:

repository:
  url: #git@github.com:ggramal/infrared.git
  revision: master
  paths:
    env_chart: argocd/charts/infra/charts/environment
    envs_chart: argocd/charts/infra/charts/environments
    root_from_chart: "../../../.."

defaultValuesTpl: |
  company:
    name: {{ .Values.company.name }}
    admins: {{ .Values.company.admins | toYaml | nindent 4 }}
    domain:
      root: {{ .Values.company.domain.root }}
      env: {{ printf "%s.%s" .env.short_name .Values.company.domain.root }}
  network:
    int_nat_gw: {{ .Values.network.int_nat_gw }}
  registry:
    url: {{ .env.registry }}
    containers:
    pip:
  bucket:
    prefix: {{ .Values.company.name }}
    suffix: {{ .env.short_name }}
  repository:
    url: {{ .Values.repository.url }}
  env:
    name: {{ .env.name }}
    server: {{ .env.server }}
    short_name: {{ .env.short_name }}

root:
  enabled: true
  labels: {}
  revision:
  finalizers: {}
  syncPolicy: {}

envs: {}
#  gcp-prd:
#    enabled: true
#    labels: {}
#    revision:
#    finalizers: {}
#    syncPolicy: {}
#  gcp-int:
#    enabled: true
#    labels: {}
#    revision:
#    finalizers: {}
#    syncPolicy: {}
