labels: {}

finalizers:
  - resources-finalizer.argocd.argoproj.io


global:
  company:
    name:
    domain:
  repo:
    type:
    provider:
    group:
    name:
    revision: master
  envs: {}

repository:
  paths:
    env_chart: argocd/charts/infra/charts/environment
    envs_chart: argocd/charts/infra/charts/environments
    root_from_chart: "../../../.."
    tfvars: "{{ .Values.repository.paths.root_from_chart }}/terraform.tfvars.json"

root:
  enabled: true
  globalFromTfVars: true
  labels: {}
  revision:
  finalizers: {}
  syncPolicy: {}
