labels: {}

company:
  name: #example
  gcp:
    enabled: false
    bucket:
      prefix:
  domain:
    root: #example.com
  network:
    int_nat_gw:

repository:
  url: #git@github.com:ggramal/infrared.git
  revision: master
  paths:
    env_chart: argocd/charts/infra/charts/environment
    envs_chart: argocd/charts/infra/charts/environments
    root_from_chart: "../../../.."

root:
  enabled: true
  labels: {}
  revision:
  finalizers: {}
  syncPolicy: {}

envs: {}
#  gcp-prd:
#    enabled: true
#    labels: {}
#    revision:
#    finalizers: {}
#    syncPolicy: {}
#  gcp-int:
#    enabled: true
#    labels: {}
#    revision:
#    finalizers: {}
#    syncPolicy: {}
