labels: {}
finalizers:
  - resources-finalizer.argocd.argoproj.io

global:
  company:
    name:
    domain:
  repo:
    type:
    provider:
    group:
    name:
    revision:
  envs: {}

repository:
  paths:
    env_chart: argocd/charts/infra/charts/environment
    envs_chart: argocd/charts/infra/charts/environments
    root_from_chart: "../../../.."

root:
  enabled: true
  labels: {}
  revision:
  finalizers: {}
  syncPolicy: {}
