global:
  company:
    name: #example
    teams:
      domain: ""
      admin:
        emails: []
      qa:
        emails: []
      dev:
        emails: []
      pm:
        emails: []
    domain:
      root: #example.com
      env: #int.example.com, dev.example.com, prd.example.com etc
  network:
    int_nat_gw:
  registry:
    url:
  bucket:
    type:
    prefix:
    suffix:
  ingress:
    class: pomerium
  env:
    name: #aws-prd or aws-int or aws-stg
    server: #https://2.2.2.2
    short_name: #pre/prd/int/dev/etc
  access:
    teams: ["dev", "admin"]
    emails: []
  pomerium:
    policy:
      default: ""

ingresses:
  main:
    enabled: false
    name: '{{ include "rabbitmq.fullname" . }}-main'
    service:
      name: '{{ include "rabbitmq.fullname" . }}-rabbitmq-main'
      port: 15672
    className: "{{ .Values.global.ingress.class }}"
    annotations:
      cert-manager.io/cluster-issuer: '{{ printf "letsencrypt-%s" .Values.global.ingress.class }}'
      ingress.pomerium.io/policy: |
        {{- tpl .Values.global.pomerium.policy.default $ | nindent 2}}
    hosts:
    - host: "rm.{{ .Values.global.company.domain.env }}"
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: rm-tls
      hosts:
      - "rm.{{ .Values.global.company.domain.env }}"

rabbitmq-cluster-operator:
  enabled: false
  useCertManager: true
  clusterOperator:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 25Mi
  msgTopologyOperator:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 25Mi

rabbitmq-main:
  enabled: false
  serviceMonitor:
    enabled: true
    selector:
      prometheus: main
###########################
# Rmq configuration example
###########################
#  annotations:
#    rabbitmq.com/topology-allowed-namespaces: "namespace1,namespace2"
#  replicas: 3
#  override:
#    statefulSet:
#      spec:
#        template:
#          metadata:
#            labels:
#              #proper labeling is needed for
#              #observability
#              app.kubernetes.io/instance: '{{ include "rabbitmq-cluster.fullname" . }}'#
#  persistence:
#    storageClassName: premium-rwo
#    storage: 10Gi
#
#  vhosts:
#    somevhost:
#      default_queue_type: quorum
