apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: chents-gcp-prd-postgres-cluster-clone
  namespace: chents
spec:
  clone:
    uid: "952bc355-b457-4ce3-b661-03cb18486a47"
    cluster: "chents-gcp-prd-postgres-cluster"
    timestamp: "2024-03-20T09:00:00+00:00"
  numberOfInstances: 1
  teamId: chents
  postgresql:
    version: '15'
  volume:
    size: 10Gi
    storageClass: premium-rwo
